# Generated by Django 4.2.10 on 2025-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="box_price",
            field=models.DecimalField(
                decimal_places=2,
                default=450.0,
                help_text="Цена за одну коробку (по умолчанию 450 руб.)",
                max_digits=10,
                verbose_name="Цена за коробку",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="pallet_prices",
            field=models.JSONField(
                default=dict,
                help_text="Цены для паллет разных весовых категорий в формате JSON",
                verbose_name="Цены для паллет",
            ),
        ),
    ]
