# Generated by Django 4.2.10 on 2025-04-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_palletpricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume_category",
                    models.CharField(
                        choices=[
                            ("small", "Маленький (до 0.1 куб.м)"),
                            ("medium", "Средний (0.1-0.2 куб.м)"),
                            ("large", "Большой (более 0.2 куб.м)"),
                        ],
                        max_length=20,
                        verbose_name="Категория объема",
                    ),
                ),
                (
                    "box_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартный"),
                            ("non_standard", "Нестандартный"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Тип коробки",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "min_volume",
                    models.FloatField(
                        default=0, verbose_name="Минимальный объем (куб.м)"
                    ),
                ),
                (
                    "max_volume",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Максимальный объем (куб.м)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Цена коробки",
                "verbose_name_plural": "Цены коробок",
                "unique_together": {("volume_category", "box_type")},
            },
        ),
    ]
