# Generated by Django 4.2.10 on 2025-04-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_boxpricing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boxpricing",
            options={
                "ordering": ["size_category", "volume_range"],
                "verbose_name": "Цена коробки",
                "verbose_name_plural": "Цены коробок",
            },
        ),
        migrations.AlterUniqueTogether(
            name="boxpricing",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="boxpricing",
            name="size_category",
            field=models.CharField(
                choices=[
                    ("60x40x40 см", "60x40x40 см"),
                    ("50x40x40 см", "50x40x40 см"),
                    ("45x45x45 см", "45x45x45 см"),
                    ("Другой размер", "Другой размер"),
                ],
                default="60x40x40 см",
                max_length=50,
                verbose_name="Размер коробки",
            ),
        ),
        migrations.AddField(
            model_name="boxpricing",
            name="volume_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("V ≤ 0.1", "До 0.1 м³"),
                    ("0.1 < V ≤ 0.2", "От 0.1 до 0.2 м³"),
                    ("V > 0.2", "Более 0.2 м³"),
                ],
                max_length=50,
                null=True,
                verbose_name="Диапазон объема",
            ),
        ),
        migrations.AlterField(
            model_name="boxpricing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="boxpricing",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена за коробку"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boxpricing",
            unique_together={("size_category", "volume_range")},
        ),
        migrations.RemoveField(
            model_name="boxpricing",
            name="box_type",
        ),
        migrations.RemoveField(
            model_name="boxpricing",
            name="max_volume",
        ),
        migrations.RemoveField(
            model_name="boxpricing",
            name="min_volume",
        ),
        migrations.RemoveField(
            model_name="boxpricing",
            name="volume_category",
        ),
    ]
