# Generated by Django 4.2.10 on 2025-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_boxpricing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="additional_services",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Дополнительные услуги"
            ),
        ),
    ]
