# Generated by Django 4.2.10 on 2025-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_sequence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="sequence_number",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Автоматически присваиваемый порядковый номер заказа",
                unique=True,
                verbose_name="Порядковый номер",
            ),
        ),
    ]
