# Generated by Django 4.2.10 on 2025-04-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_sequence_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="ФИО водителя"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Водитель",
                "verbose_name_plural": "Водители",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Марка")),
                (
                    "plate_number",
                    models.CharField(max_length=20, unique=True, verbose_name="Номер"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Грузовик",
                "verbose_name_plural": "Грузовики",
                "ordering": ["brand", "plate_number"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="driver_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата назначения водителя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.driver",
                verbose_name="Водитель",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.truck",
                verbose_name="Грузовик",
            ),
        ),
    ]
