# Generated by Django 4.2.10 on 2025-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_driver_truck_order_driver_assigned_at_order_driver_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Водитель",
                "verbose_name_plural": "Водители",
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
    ]
