# Generated by Django 4.2.10 on 2025-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_driver_options_driver_phone_driver_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="truck",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Грузовик",
                "verbose_name_plural": "Грузовики",
            },
        ),
        migrations.AddField(
            model_name="truck",
            name="truck_model",
            field=models.CharField(default="", max_length=100, verbose_name="Модель"),
        ),
        migrations.AddField(
            model_name="truck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="truck",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="Марка"),
        ),
        migrations.AlterField(
            model_name="truck",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="truck",
            name="plate_number",
            field=models.CharField(max_length=20, verbose_name="Гос. номер"),
        ),
    ]
